language: go

go:
  - tip

services:
  - redis-server

before_install:
  - mkdir -p $GOPATH/src/gopkg.in/gilmour-libs
  - ln -s $(pwd) $GOPATH/src/gopkg.in/gilmour-libs/gilmour-e-go.v5

script:
  - go test -v --race ./...
  - go build -v --race ./...

notifications:
  email:
    - piyush@piyushverma.net
